server:
  port: 8084

spring:
  autoconfigure:
    #自动化配置 例外处理
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456

    #多数据源配置
    dynamic:
      druid: #以下是全局默认值，可以全局更改
        #监控统计拦截的filters
        filters: stat
        #配置初始化大小/最小/最大
        initial-size: 1
        min-idle: 1
        max-active: 20
        #获取连接等待超时时间
        max-wait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x' FROM dual
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 3000

      primary: master
      strict: false

      datasource:
        # 应用库
        master:
          url: jdbc:oracle:thin:@localhost:1521:xe
          username: scott
          password: scott
        # 业务库（同步到kafka）
        biz:
          url: jdbc:oracle:thin:@localhost:1521:xe
          username: scott
          password: scott

  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss

kafka:
  connect:
    url: http://localhost:8083/connectors

logging:
  level:
    com.striveh.pushdata: debug
    root: info
  file:
    name: logs/pushdata.log